<?php

namespace VulnerabilidadBundle\Repository;

/**
 * VulnerabilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VulnerabilidadRepository extends \Doctrine\ORM\EntityRepository
{
}
