<?php

namespace VulnerabilidadCatBundle\Repository;

/**
 * Cat_VulnerabilidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cat_VulnerabilidadRepository extends \Doctrine\ORM\EntityRepository
{
}
