insert into amenaza values
(1, '1','Incendio'),
(2, '1','Terremoto'),
(3, '2','Degradación de los soportes de almacenamiento de la información'),
(4, '2','Avería de orígen físico o lógico'),
(5, '2','Condiciones inadecuadas de temperatura o humedad'),
(6, '2','Fallo de servicios de comunicaciones'),
(7, '2','Interrupción de otros servicios o suministros esenciales'),
(8, '3','Errores de usuarios'),
(9, '3','Errores del administrador del sistema (seguridad)'),
(10, '3','Errores de monitorización (log)'),
(11, '3','Errores de configuración'),
(12, '3','Deficiencias en la organización'),
(13, '3','Difusión de software dañino'),
(14, '3','Fugas de información'),
(15, '3','Alteración de la información'),
(16, '3','Vulnerabilidades en software'),
(17, '3','Caída del sistema por agotamiento de recursos'),
(18, '3','Pérdida de equipos'),
(19, '3','Indisponibilidad de personal'),
(20, '4','Manipulación de los registros de actividad (log)'),
(21, '4','Manipulación de ficheros de configuración'),
(22, '4','Suplantación de identidad'),
(23, '4','Abuso de privilegios de acceso'),
(24, '4','Difusión de software dañino'),
(25, '4','Destrucción de la información'),
(26, '4','Manipulación del hadware'),
(27, '4','Manipulación de programas'),
(28, '4','Denegación de servicio'),
(29, '4','Robo de equipos'),
(30, '4','Ataque destructivo');
