insert into control values
(1, 'Políticas de seguridad', 'Directrices de la Dirección en seguridad de la información', 'Conjunto de políticas para la seguridad de la información'),
(2, 'Políticas de seguridad', 'Directrices de la Dirección en seguridad de la información', 'Revisión de las políticas para la seguridad de la información'),
(3, 'Aspectos organizativos de la seguridad de la información', 'Organización interna', 'Asignación de responsabilidades para la segur. de la información'),
(4, 'Aspectos organizativos de la seguridad de la información', 'Organización interna', 'Segregación de tareas'),
(5, 'Aspectos organizativos de la seguridad de la información', 'Organización interna', 'Contacto con las autoridades'),
(6, 'Aspectos organizativos de la seguridad de la información', 'Organización interna', 'Contacto con grupos de interés especial'),
(7, 'Aspectos organizativos de la seguridad de la información', 'Organización interna', 'Seguridad de la información en la gestión de proyectos'),
(8, 'Aspectos organizativos de la seguridad de la información', 'Dispositivos para movilidad y teletrabajo', 'Política de uso de dispositivos para movilidad'),
(9, 'Aspectos organizativos de la seguridad de la información', 'Dispositivos para movilidad y teletrabajo','Teletrabajo'),
(10, 'Seguridad ligada a los recursos humanos', 'Antes de la contratación', 'Investigación de antecedentes'),
(11, 'Seguridad ligada a los recursos humanos', 'Antes de la contratación', 'Términos y condiciones de contratación'),
(12, 'Seguridad ligada a los recursos humanos', 'Durante la contratación', 'Responsabilidades de gestión'),
(13, 'Seguridad ligada a los recursos humanos', 'Durante la contratación', 'Concienciación, educación y capacitación en segur. de la información'),
(14, 'Seguridad ligada a los recursos humanos', 'Durante la contratación', 'Proceso disciplinario'),
(15, 'Seguridad ligada a los recursos humanos', 'Cese o cambio de puesto de trabajo', 'Cese o cambio de puesto de trabajo'),
(16, 'Gestión de activos', 'Responsabilidad sobre los activos', 'Inventario de activos'),
(17, 'Gestión de activos', 'Responsabilidad sobre los activos', 'Propiedad de los activos'),
(18, 'Gestión de activos', 'Responsabilidad sobre los activos', 'Uso aceptable de los activos'),
(19, 'Gestión de activos', 'Responsabilidad sobre los activos', 'Devolución de activos'),
(20, 'Gestión de activos', 'Clasificación de la información', 'Directrices de clasificación'),
(21, 'Gestión de activos', 'Clasificación de la información', 'Etiquetado y manipulado de la información'),
(22, 'Gestión de activos', 'Clasificación de la información', 'Manipulación de activos'),
(23, 'Gestión de activos', 'Manejo de los soportes de almacenamiento', 'Gestión de soportes extraíbles'),
(24, 'Gestión de activos', 'Manejo de los soportes de almacenamiento', 'Eliminación de soportes'),
(25, 'Gestión de activos', 'Manejo de los soportes de almacenamiento', 'Soportes físicos en tránsito'),
(26, 'Control de accesos', 'Requisitos de negocio para el control de accesos', 'Política de control de accesos'),
(27, 'Control de accesos', 'Requisitos de negocio para el control de accesos', 'Control de acceso a las redes y servicios asociados'),
(28, 'Control de accesos', 'Gestión de acceso de usuario', 'Gestión de altas/bajas en el registro de usuarios'),
(29, 'Control de accesos', 'Gestión de acceso de usuario', 'Gestión de los derechos de acceso asignados a usuarios'),
(30, 'Control de accesos', 'Gestión de acceso de usuario', 'Gestión de los derechos de acceso con privilegios especiales'),
(31, 'Control de accesos', 'Gestión de acceso de usuario', 'Gestión de información confidencial de autenticación de usuarios'),
(32, 'Control de accesos', 'Gestión de acceso de usuario', 'Revisión de los derechos de acceso de los usuarios'),
(33, 'Control de accesos', 'Gestión de acceso de usuario', 'Retirada o adaptación de los derechos de acceso'),
(34, 'Control de accesos', 'Responsabilidades del usuario', 'Uso de información confidencial para la autenticación.'),
(35, 'Control de accesos', 'Control de acceso a sistemas y aplicaciones', 'Restricción del acceso a la información'),
(36, 'Control de accesos', 'Control de acceso a sistemas y aplicaciones', 'Procedimientos seguros de inicio de sesión'),
(37, 'Control de accesos', 'Control de acceso a sistemas y aplicaciones', 'Gestión de contraseñas de usuario'),
(38, 'Control de accesos', 'Control de acceso a sistemas y aplicaciones', 'Uso de herramientas de administración de sistemas'),
(39, 'Control de accesos', 'Control de acceso a sistemas y aplicaciones', 'Control de acceso al código fuente de los programas'),

(40, 'Cifrado', 'Controles criptográficos', 'Política de uso de los controles criptográficos'),
(41, 'Cifrado', 'Controles criptográficos', 'Gestión de claves'),
(42, 'Seguridad física y ambiental', 'Áreas seguras', 'Perímetro de seguridad física.'),
(43, 'Seguridad física y ambiental', 'Áreas seguras', 'Controles físicos de entrada'),
(44, 'Seguridad física y ambiental', 'Áreas seguras', 'Seguridad de oficinas, despachos y recursos'),
(45, 'Seguridad física y ambiental', 'Áreas seguras', 'Protección contra las amenazas externas y ambientales'),
(46, 'Seguridad física y ambiental', 'Áreas seguras', 'El trabajo en áreas seguras'),
(47, 'Seguridad física y ambiental', 'Áreas seguras', 'Áreas de acceso público, carga y descarga'),
(48, 'Seguridad física y ambiental', 'Seguridad de los equipos', 'Emplazamiento y protección de equipos'),
(49, 'Seguridad física y ambiental', 'Seguridad de los equipos', 'Instalaciones de suministro'),
(50, 'Seguridad física y ambiental', 'Seguridad de los equipos', 'Seguridad del cableado'),
(51, 'Seguridad física y ambiental', 'Seguridad de los equipos', 'Mantenimiento de los equipos.'),
(52, 'Seguridad física y ambiental', 'Seguridad de los equipos', 'Salida de activos fuera de las dependencias de la empresa'),
(53, 'Seguridad física y ambiental', 'Seguridad de los equipos', 'Seguridad de los equipos y activos fuera de las instalaciones.'),
(54, 'Seguridad física y ambiental', 'Seguridad de los equipos', 'Reutilización o retirada segura de dispositivos de almacenamiento'),
(55, 'Seguridad física y ambiental', 'Seguridad de los equipos', 'Equipo informático de usuario desatendido'),
(56, 'Seguridad física y ambiental', 'Seguridad de los equipos', 'Política de puesto de trabajo despejado y bloqueo de pantalla.'),
(57, 'Seguridad en la operativa', 'Responsabilidades y procedimientos de operación', 'Documentación de procedimientos de operación'),
(58, 'Seguridad en la operativa', 'Responsabilidades y procedimientos de operación', 'Gestión de cambios'),
(59, 'Seguridad en la operativa', 'Responsabilidades y procedimientos de operación', 'Gestión de capacidades'),
(60, 'Seguridad en la operativa', 'Responsabilidades y procedimientos de operación', 'Separación de entornos de desarrollo, prueba y producción'),
(61, 'Seguridad en la operativa', 'Protección contra código malicioso', 'Controles contra el código malicioso.'),
(62, 'Seguridad en la operativa', 'Copias de seguridad', 'Copias de seguridad de la información'),
(63, 'Seguridad en la operativa', 'Registro de actividad y supervisión', 'Registro y gestión de eventos de actividad'),
(64, 'Seguridad en la operativa', 'Registro de actividad y supervisión', 'Protección de los registros de información'),
(65, 'Seguridad en la operativa', 'Registro de actividad y supervisión', 'Registros de actividad del administrador y operador del sistema'),
(66, 'Seguridad en la operativa', 'Registro de actividad y supervisión', 'Sincronización de relojes.'),
(67, 'Seguridad en la operativa', 'Control del software en explotación', 'Instalación del software en sistemas en producción'),
(68, 'Seguridad en la operativa', 'Gestión de la vulnerabilidad técnica', 'Gestión de las vulnerabilidades técnicas'),
(69, 'Seguridad en la operativa', 'Gestión de la vulnerabilidad técnica', 'Restricciones en la instalación de software'),
(70, 'Seguridad en la operativa', 'Consideraciones de las auditorías de los sistemas de información.', 'Controles de auditoría de los sistemas de información'),
(71, 'Seguridad en las Telecomunicaciones', 'Gestión de la seguridad en las redes', 'Controles de red'),
(72, 'Seguridad en las Telecomunicaciones', 'Gestión de la seguridad en las redes', 'Mecanismos de seguridad asociados a servicios en red'),
(73, 'Seguridad en las Telecomunicaciones', 'Gestión de la seguridad en las redes', 'Segregación de redes'),
(74, 'Seguridad en las Telecomunicaciones', 'Intercambio de información con partes externas', 'Políticas y procedimientos de intercambio de información'),
(75, 'Seguridad en las Telecomunicaciones', 'Intercambio de información con partes externas', 'Acuerdos de intercambio'),
(76, 'Seguridad en las Telecomunicaciones', 'Intercambio de información con partes externas', 'Mensajería electrónica'),
(77, 'Seguridad en las Telecomunicaciones', 'Intercambio de información con partes externas', 'Acuerdos de confidencialidad y secreto'),

(78, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Requisitos de seguridad de los sistemas de información', 'Análisis y especificación de los requisitos de seguridad'),
(79, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Requisitos de seguridad de los sistemas de información', 'Seguridad de las comunicaciones en servicios accesibles por redes
públicas'),
(80, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Requisitos de seguridad de los sistemas de información', 'Protección de las transacciones por redes telemáticas'),
(81, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Seguridad en los procesos de desarrollo y soporte', 'Política de desarrollo seguro de software'),
(82, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Seguridad en los procesos de desarrollo y soporte', 'Procedimientos de control de cambios en los sistemas'),
(83, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Seguridad en los procesos de desarrollo y soporte', 'Revisión técnica de las aplicaciones tras efectuar cambios en el
sistema operativo.'),
(84, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Seguridad en los procesos de desarrollo y soporte', 'Restricciones a los cambios en los paquetes de software'),
(85, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Seguridad en los procesos de desarrollo y soporte', 'Uso de principios de ingeniería en protección de sistemas.'),
(86, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Seguridad en los procesos de desarrollo y soporte', 'Seguridad en entornos de desarrollo'),
(87, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Seguridad en los procesos de desarrollo y soporte', 'Externalización del desarrollo de software'),
(88, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Seguridad en los procesos de desarrollo y soporte', 'Pruebas de funcionalidad durante el desarrollo de los sistemas'),
(89, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Seguridad en los procesos de desarrollo y soporte', 'Pruebas de aceptación'),
(90, 'Adquisición, desarrollo y mantenimiento de los sistemas de información', 'Datos de prueba', 'Protección de los datos utilizados en pruebas'),
(91, 'Relaciones con suministradores', 'Seguridad de la información en las relaciones con suministradores', 'Política de seguridad de la información para suministradores'),
(92, 'Relaciones con suministradores', 'Seguridad de la información en las relaciones con suministradores', 'Tratamiento del riesgo dentro de acuerdos de suministradores'),
(93, 'Relaciones con suministradores', 'Seguridad de la información en las relaciones con suministradores', 'Cadena de suministro en tecnologías de la información y
comunicaciones'),
(94, 'Relaciones con suministradores', 'Gestión de la prestación del servicio por suministradores', 'Supervisión y revisión de los servicios prestados por terceros'),
(95, 'Relaciones con suministradores', 'Gestión de la prestación del servicio por suministradores', 'Gestión de cambios en los servicios prestados por terceros'),
(96, 'Gestión de Incidentes en la Seguridad de la Información', 'Gestión de incidentes de seguridad de la información y mejoras', 'Responsabilidades y procedimientos'),
(97, 'Gestión de Incidentes en la Seguridad de la Información', 'Gestión de incidentes de seguridad de la información y mejoras', 'Notificación de los eventos de seguridad de la información'),
(98, 'Gestión de Incidentes en la Seguridad de la Información', 'Gestión de incidentes de seguridad de la información y mejoras', 'Notificación de puntos débiles de la seguridad'),
(99, 'Gestión de Incidentes en la Seguridad de la Información', 'Gestión de incidentes de seguridad de la información y mejoras', 'Valoración de eventos de seguridad de la información y toma de
decisiones'),
(100, 'Gestión de Incidentes en la Seguridad de la Información', 'Gestión de incidentes de seguridad de la información y mejoras', 'Respuesta a los incidentes de seguridad'),
(101, 'Gestión de Incidentes en la Seguridad de la Información', 'Gestión de incidentes de seguridad de la información y mejoras', 'Aprendizaje de los incidentes de seguridad de la información.'),
(102, 'Gestión de Incidentes en la Seguridad de la Información', 'Gestión de incidentes de seguridad de la información y mejoras', 'Recopilación de evidencias'),
(103, 'Aspectos de Seguridad de la Información en la Gestión de la Continuidad del Negocio', 'Continuidad de la seguridad de la información', 'Planificación de la continuidad de la seguridad de la información'),
(104, 'Aspectos de Seguridad de la Información en la Gestión de la Continuidad del Negocio', 'Continuidad de la seguridad de la información', 'Implantación de la continuidad de la seguridad de la información'),
(105, 'Aspectos de Seguridad de la Información en la Gestión de la Continuidad del Negocio', 'Continuidad de la seguridad de la información', 'Verificación, revisión y evaluación de la continuidad de la seguridad
de la información'),
(106, 'Aspectos de Seguridad de la Información en la Gestión de la Continuidad del Negocio', 'Redundancias', 'Disponibilidad de instalaciones para el procesamiento de la
información'),
(107, 'Cumplimiento', 'Cumplimiento de los requisitos legales y contractuales', 'Identificación de la legislación aplicable'),
(108, 'Cumplimiento', 'Cumplimiento de los requisitos legales y contractuales', 'Derechos de propiedad intelectual (DPI)'),
(109, 'Cumplimiento', 'Cumplimiento de los requisitos legales y contractuales', 'Protección de los registros de la organización'),
(110, 'Cumplimiento', 'Cumplimiento de los requisitos legales y contractuales', 'Protección de datos y privacidad de la información personal'),
(111, 'Cumplimiento', 'Cumplimiento de los requisitos legales y contractuales', 'Regulación de los controles criptográficos'),
(112, 'Cumplimiento', 'Revisiones de la seguridad de la información', 'Revisión independiente de la seguridad de la información'),
(113, 'Cumplimiento', 'Revisiones de la seguridad de la información', 'Cumplimiento de las políticas y normas de seguridad'),
(114, 'Cumplimiento', 'Revisiones de la seguridad de la información', 'Comprobación del cumplimiento');

