<?php

namespace RiesgoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RiesgoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiesgoRepository extends EntityRepository
{
}
