<?php

namespace ControlactivoBundle\Repository;

/**
 * ControlactivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlactivoRepository extends \Doctrine\ORM\EntityRepository
{
}
