plan_tratamiento_plan.tratamiento:
    resource: "@PlanTratamientoBundle/Controller/Plan_TratamientoController.php"
    type:     annotation

categoria_plan_categoria.plan:
    resource: "@CategoriaPlanBundle/Controller/Categoria_PlanController.php"
    type:     annotation

categoria_plan:
    resource: "@CategoriaPlanBundle/Resources/config/routing.yml"
    prefix:   /categoria_plan

plan_tratamiento:
    resource: "@PlanTratamientoBundle/Resources/config/routing.yml"
    prefix:   /plan_tratamiento


amenaza_amenaza:
    resource: "@AmenazaBundle/Controller/AmenazaController.php"
    type:     annotation

amenaza_cat_cat.amenaza:
    resource: "@AmenazaCatBundle/Controller/Cat_AmenazaController.php"
    type:     annotation

vulnerabilidad_cat:
    resource: "@VulnerabilidadCatBundle/Resources/config/routing.yml"
    prefix:   /vulnerabilidad_cat

vulnerabilidad:
    resource: "@VulnerabilidadBundle/Resources/config/routing.yml"
    prefix:   /vulnerabilidad

riesgo:
    resource: "@RiesgoBundle/Controller/RiesgoController.php"
    type:     annotation
    prefix: /riesgo


amenaza:
    resource: "@AmenazaBundle/Resources/config/routing.yml"
    prefix:   /amenaza

amenaza_cat:
    resource: "@AmenazaCatBundle/Resources/config/routing.yml"
    prefix:   /cat_amenazas

categoria:
    resource: "@CategoriaBundle/Controller/"
    type:     annotation
    prefix:   /categoria

activo:
    resource: "@ActivoBundle/Controller/"
    type:     annotation
    prefix:   /activo

user_usuario:
    resource: "@UserBundle/Controller/UsuarioController.php"
    type:     annotation

empresa_empresa:
    resource: "@EmpresaBundle/Controller/EmpresaController.php"
    type:     annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

empresa:
    resource: "@EmpresaBundle/Resources/config/routing.yml"
    prefix:   /empresa
    
login_check:
    pattern: /login_check 

app:
    resource: '@AppBundle/Controller/'
    type: annotation

menu_categoria:
    resource: "@CategoriaBundle/Controller/categoriaController.php"
    type:     annotation


menu_activo:
    resource: "@ActivoBundle/Controller/activoController.php"
    type:     annotation


menu_riesgo:
    resource: "@RiesgoBundle/Controller/RiesgoController.php"
    type:     annotation







