<?php

namespace AmenazaCatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Cat_AmenazaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cat_AmenazaRepository extends EntityRepository
{
}
