<?php

namespace PlanTratamientoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Plan_TratamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Plan_TratamientoRepository extends EntityRepository
{
}
