<?php

namespace AmenazaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AmenazaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmenazaRepository extends EntityRepository
{
}
