<?php

namespace CategoriaPlanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Categoria_PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categoria_PlanRepository extends EntityRepository
{
}
